### PR TITLE
portage python 3.5

### PR DESCRIPTION
**Pull request by cokelaer**
This is not a complete portage. The only test I did was to run something like:

```
quast.py test.contigs.fasta test.scaffolds.fasta -o quast_test
```

this of course does not test the entire package but reports and output files seems to be correctly generated for that example. 

More work would be required for the test suite. I hope this help though and that it can be incorporated in the main package. 

Note that the trickiest part was to understand the parsing of the strings such as the contig_thresholds into a proper tuple. I also had to change some *print >>* statements to use .write method of the file handler. Of course a print(msg, file=handler) could be used (I thought about it too late). 

As for the job lib changes you mentioned in https://github.com/ablab/quast/commit/dc02f72440b278c6e15188fe8f29f0a3ccee9f11 I believe a merge can be performed later on.

I had changed one file in joblib/ only but it is far better to use the official joblib version as you did.

Lots of maps have been changed to list comprehensions.

The xrange were changed to range. I understand that this mean a less efficient code in Python2 but this keeps the code simple. I do not think this is the bottleneck in the code anyway.

Let me know if modifications are not clear.

### CODE REVIEW

**Comment by alexeigurevich** [comment]
Thanks for all these changes!
Almost everything looks perfect but could you please make one more simple modification. You substituted try-except constructions in the following manner:
         try:
              zfile = zipfile.ZipFile(fpath)
 -        except Exception, e:
 -            logger.error('Can\'t open zip file: ' + str(e.message))
 +        except Exception as err:
 +            logger.error('Can\'t open zip file: ' + str(err))

This is fine for python3 and python2.7 but it is incorrect syntax in python2.5 which is still supported by Quast. Could you please use more general syntax which is working in both python2 and python3:
          
       except Exception:
              exc_type, exc_value, _ = sys.exc_info()
              logger.error('Can\'t open zip file: ' + str(exc_value))

Thanks!

**Comment by cokelaer** [comment]
FYI: tc_tests directory will need to be revisited as well for python3 portage

**Comment by alexeigurevich** [comment]
Sorry for not being explicit: I meant to change all your updates in try-except constructions in the python2.5 compatible manner (in about 7 places).

About tc_tests -- yes, thank you for noticing!

**Comment by cokelaer** [comment]
I believe I fixed the exceptions now but let me know if there is something else.

**Comment by alexeigurevich** [comment]
I found few cases in two more files: 
quast_libs/ra_utils.py
quast_libs/site_packages/jsontemplate/jsontemplate.py

The rest are fine!

**Comment by alexeigurevich** [comment]
Everything merged + I added few tiny fixes

**Comment by cokelaer** [comment]
great. thanks

**Pull request merged**
